title : APIs.json

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: api-json
destination: api-json

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 500
paginate_path: "/blog/page:num"

production_url : http://apisjson.org

BASE_PATH : http://apisjson.org

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
